import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Firebase configuration & initialisation helper.
///
/// **Setup instructions:**
///
/// 1. Create a Firebase project at https://console.firebase.google.com
///
/// 2. Add platform apps and download config files:
///    - **Android:** download `google-services.json` and place it in
///      `android/app/google-services.json`
///    - **iOS:** download `GoogleService-Info.plist` and place it in
///      `ios/Runner/GoogleService-Info.plist`
///    - The Firebase CLI command `flutterfire configure` automates this
///      and also generates a `lib/firebase_options.dart` file. Either path
///      is fine — this service tries the platform default first.
///
/// 3. In the Firebase console, enable **Cloud Firestore** (Database →
///    Create database → start in test mode for development). The app
///    creates collections on demand; no manual schema needed.
///
/// 4. **Recommended Firestore data model** (created automatically as the
///    app writes data; included here for reference and security-rule
///    authoring):
///
///    ```
///    profiles/{profileId}
///      - id, name, role, avatarIndex, createdAt, disabilityType,
///        classroomId, isGuestPlayer
///
///    progress/{profileId}
///      - profileId, wordsLearned, streakDays, lastActivity,
///        categoryProgress (map), recentScores (array), totalStars,
///        spentStars, classroomId
///
///    custom_cards/{cardId}
///      - id, wordEnglish, wordFilipino, exampleSentence, imageAsset,
///        category, profileId
///
///    achievements/{profileId}/items/{achievementId}
///    shop_purchases/{profileId}/items/{itemId}
///    shop_equipped/{profileId}_{type}
///
///    classrooms/{classroomId}
///      - id, code (UNIQUE — enforce via security rules), name,
///        teacherId, createdAt, updatedAt
///
///    classroom_members/{classroomId}_{profileId}
///      - classroomId, profileId, displayName, joinedAt
///
///    session_logs/{autoId}
///      - profileId, date, durationSeconds, gamesPlayed, cardsReviewed
///
///    app_state/{key}
///      - key, value
///    ```
///
/// 5. **Recommended Firestore security rules** (paste into Rules tab,
///    relax for development; tighten before production):
///
///    ```
///    rules_version = '2';
///    service cloud.firestore {
///      match /databases/{database}/documents {
///        match /{document=**} {
///          allow read, write: if true;  // DEVELOPMENT ONLY
///        }
///      }
///    }
///    ```
class FirebaseService {
  FirebaseService._();

  /// Whether Firebase has been initialised successfully.
  static bool _initialised = false;

  /// Whether Firebase config is reachable.
  /// True after a successful [init]. Used by [LocalRepository._enqueue]
  /// and [JoinCodeService] to gate cloud writes.
  static bool get isConfigured => _initialised;

  /// The default Firestore client (available after [init]).
  ///
  /// Reads/writes through this instance benefit from Firestore's built-in
  /// offline persistence on mobile platforms — pending writes survive
  /// app restarts and replay automatically when the device reconnects.
  static FirebaseFirestore get db => FirebaseFirestore.instance;

  /// Anonymous-auth UID for this device, or null if sign-in hasn't
  /// completed yet (first launch offline, or Firebase init failed).
  /// Stamped onto every owner-scoped Firestore write so security rules
  /// can verify the writer.
  static String? get currentUid => FirebaseAuth.instance.currentUser?.uid;

  /// The reason init failed (when [isConfigured] is false). Surfaced in
  /// the UI banner and logs so the developer can act on it.
  static String? lastInitError;

  /// Initialise Firebase. Safe to call multiple times.
  ///
  /// Pass [options] from `DefaultFirebaseOptions.currentPlatform`
  /// (generated by `flutterfire configure`) — this is **required on web**
  /// and recommended on every platform for explicit project pinning.
  ///
  /// On Android/iOS, [options] may be omitted IF `google-services.json` /
  /// `GoogleService-Info.plist` are wired up via the Google Services
  /// Gradle plugin / Xcode runtime config — but this auto-detection
  /// requires `flutterfire configure` to have patched the platform build
  /// files. The CLI is the supported, low-friction path.
  ///
  /// On failure, [isConfigured] stays false and [lastInitError] holds
  /// the reason. The app continues offline-only.
  static Future<void> init({FirebaseOptions? options}) async {
    if (_initialised) return;
    try {
      if (options != null) {
        await Firebase.initializeApp(options: options);
      } else {
        await Firebase.initializeApp();
      }
      // Enable offline persistence (mobile platforms enable it by default
      // but setting it explicitly documents intent and survives platform
      // upgrades). Wrapped in try/catch because the call is a no-op on
      // platforms where it's already on.
      try {
        FirebaseFirestore.instance.settings = const Settings(
          persistenceEnabled: true,
          cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
        );
      } catch (_) {
        // Settings may already be locked in if Firestore was touched
        // before this point — safe to ignore.
      }
      _initialised = true;
      lastInitError = null;
      if (kDebugMode) {
        debugPrint('✓ FirebaseService: connected to '
            '${Firebase.app().options.projectId}');
      }
    } catch (e, stack) {
      lastInitError = e.toString();
      if (kDebugMode) {
        debugPrint('✗ FirebaseService.init failed: $e\n$stack');
        debugPrint('  → Run `flutterfire configure` from the project root '
            'to generate firebase_options.dart and platform configs.');
      }
      _initialised = false;
    }
  }

  /// Sign in anonymously so every Firestore write carries a verifiable
  /// `request.auth.uid`. Anonymous Auth keeps the kid-facing UX unchanged
  /// (no sign-up, no password) while giving security rules an identity to
  /// pin owner-scoped data to.
  ///
  /// Idempotent: returns immediately if a user is already signed in.
  /// Non-throwing: failures (offline first-launch, Auth disabled in the
  /// Firebase console) are logged and the app continues offline-only.
  static Future<void> signInAnonymously() async {
    if (!_initialised) return;
    if (FirebaseAuth.instance.currentUser != null) return;
    try {
      await FirebaseAuth.instance.signInAnonymously();
      if (kDebugMode) {
        debugPrint('✓ FirebaseService: anonymous uid '
            '${FirebaseAuth.instance.currentUser?.uid}');
      }
    } catch (e, stack) {
      if (kDebugMode) {
        debugPrint('✗ FirebaseService.signInAnonymously failed: $e\n$stack');
        debugPrint('  → Enable Anonymous sign-in in the Firebase console: '
            'Authentication → Sign-in method → Anonymous → Enable.');
      }
    }
  }
}
