// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpF2lz17uhYXaJkMClptVR8PhITbDHKoM',
    appId: '1:905710485263:web:53faec7033926d8a8fc87a',
    messagingSenderId: '905710485263',
    projectId: 'pwd-flashcard',
    authDomain: 'pwd-flashcard.firebaseapp.com',
    storageBucket: 'pwd-flashcard.firebasestorage.app',
    measurementId: 'G-HEQQ44VL2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxDwf2oqp6Y0HW_VSxcqt4ZTYDWGgCnxg',
    appId: '1:905710485263:android:0ba72d9f961c6a6c8fc87a',
    messagingSenderId: '905710485263',
    projectId: 'pwd-flashcard',
    storageBucket: 'pwd-flashcard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoCfFpuU0K-E0finjON9t68Ugm1xRMdlk',
    appId: '1:905710485263:ios:632677a947c37b2c8fc87a',
    messagingSenderId: '905710485263',
    projectId: 'pwd-flashcard',
    storageBucket: 'pwd-flashcard.firebasestorage.app',
    iosBundleId: 'com.example.pwdpwdpwd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoCfFpuU0K-E0finjON9t68Ugm1xRMdlk',
    appId: '1:905710485263:ios:632677a947c37b2c8fc87a',
    messagingSenderId: '905710485263',
    projectId: 'pwd-flashcard',
    storageBucket: 'pwd-flashcard.firebasestorage.app',
    iosBundleId: 'com.example.pwdpwdpwd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpF2lz17uhYXaJkMClptVR8PhITbDHKoM',
    appId: '1:905710485263:web:b279e8a3c249ece88fc87a',
    messagingSenderId: '905710485263',
    projectId: 'pwd-flashcard',
    authDomain: 'pwd-flashcard.firebaseapp.com',
    storageBucket: 'pwd-flashcard.firebasestorage.app',
    measurementId: 'G-DM5T3F2T64',
  );
}
