import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'l10n/app_localizations.dart';
import 'core/security/owner_uid_migration.dart';
import 'core/security/pin_migration.dart';
import 'core/services/active_time_tracker.dart';
import 'core/services/alarm_scheduler.dart';
import 'core/services/notification_service.dart';
import 'core/services/firebase_service.dart';
import 'core/services/profile_sync_listener.dart';
import 'core/services/progress_sync_listener.dart';
import 'core/services/sync_service.dart';
import 'data/models/alarm_action.dart';
import 'data/models/enums.dart';
import 'data/models/models.dart';
import 'features/classroom/widgets/lock_enforcer_gate.dart';
import 'features/onboarding/widgets/membership_eviction_gate.dart';
// Generated by `flutterfire configure` — required for web and recommended
// on all platforms. If you haven't run that command yet, see the README.
import 'firebase_options.dart';
import 'core/theme/app_theme.dart';
import 'core/utils/error_handler.dart';
import 'data/local/hive_service.dart';
import 'data/local/local_repository.dart';
import 'data/remote/firestore_repository.dart';
import 'data/models/shop_data.dart';
import 'navigation/app_router.dart';
import 'providers/app_providers.dart';
import 'widgets/connectivity_banner.dart';
import 'widgets/error_boundary.dart';
import 'core/services/sync_queue/sync_queue_service.dart';
import 'widgets/sync_status_widget.dart';

void main() {
  // Wrap the entire startup in a guarded zone so that
  // ensureInitialized() and runApp() share the SAME zone.
  // This prevents the "Zone mismatch" error.
  ErrorHandler.runGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Install global error handling FIRST
    ErrorHandler.init();
    setupErrorWidget();

    // ─── High Refresh-Rate Performance Configuration ──────
    // Flutter 3.x automatically targets the display's native refresh rate
    // (120 Hz on Honor Pad X8a) so no manual configuration is needed.

    // Enable pointer-event resampling to align touch events with frame
    // boundaries — reduces perceived input latency on high-Hz displays.
    GestureBinding.instance.resamplingEnabled = true;

    // Increase decoded image cache for a 4 GB device with heavy flashcard
    // images. Default is 100 MB; we raise to 256 MB so scrolling large
    // grids doesn't repeatedly decode the same assets.
    PaintingBinding.instance.imageCache.maximumSizeBytes = 256 << 20; // 256 MB
    PaintingBinding.instance.imageCache.maximumSize = 200; // up to 200 images

    // Prevent Google Fonts from making HTTP requests at runtime.
    // Fonts are bundled in the google_fonts/ directory instead.
    // This avoids ANR on devices with slow or no internet.
    GoogleFonts.config.allowRuntimeFetching = false;

    // Lock to portrait on tablets
    await SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    // Transparent status bar
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
      ),
    );

    // Initialize Hive, Firebase, and Notifications in parallel
    // (they are independent of each other)
    await Future.wait([
      HiveService.init(),
      FirebaseService.init(options: DefaultFirebaseOptions.currentPlatform),
      NotificationService.init(
        onNotificationTap: (payload) {
          WidgetsBinding.instance.addPostFrameCallback((_) {
            final ctx = rootNavigatorKey.currentContext;
            if (ctx == null) return;
            switch (payload) {
              case 'daily_challenge':
                GoRouter.of(ctx).go('/home');
              case 'vocab_review':
                GoRouter.of(ctx).go('/smart-review');
              default:
                GoRouter.of(ctx).go('/home');
            }
          });
        },
      ),
    ]);

    // Open the error logs box (after Hive.init)
    await Hive.openBox('error_logs');

    // Sign in anonymously so every Firestore write carries an auth uid.
    // Must run before OwnerUidMigration (which stamps that uid onto
    // pre-auth profiles) and before any sync/queue activity.
    await FirebaseService.signInAnonymously();

    // Migrate any plaintext PINs to salted PBKDF2 hashes. Idempotent —
    // a settings flag and per-profile guards prevent double-hashing.
    await PinMigration.runIfNeeded();

    // Claim ownership of pre-auth profiles for this device's uid.
    // Idempotent — a Hive flag prevents re-runs.
    await OwnerUidMigration.runIfNeeded();

    // Start offline-first sync service (after Firebase init)
    SyncService? syncInstance;
    SyncQueueService? queueInstance;
    ProgressSyncListener? progressListener;
    ProfileSyncListener? profileListener;
    if (FirebaseService.isConfigured) {
      syncInstance = SyncService(
        local: const LocalRepository(),
        remote: const FirestoreRepository(),
      );
      syncInstance.startListening();
      queueInstance = syncInstance.queueService;

      // Process any pending queue items if we're online at launch
      queueInstance?.processQueue();

      // Bidirectional sync: subscribe to remote progress for every
      // profile on this device so updates from other devices land in
      // Hive and refresh the UI without a manual reload.
      progressListener = ProgressSyncListener();
      progressListener.start();

      // Mirror listener for `profiles/{id}` — picks up educator-driven
      // name patches (Manage Classes > Rename, Home Group > Rename) so
      // the learner's own device shows the new name without a relaunch.
      profileListener = ProfileSyncListener();
      profileListener.start();
    }

    runApp(ProviderScope(
      overrides: [
        if (syncInstance != null)
          syncServiceProvider.overrideWithValue(syncInstance),
        if (queueInstance != null)
          syncQueueServiceProvider.overrideWithValue(queueInstance),
        if (progressListener != null)
          progressSyncListenerProvider.overrideWithValue(progressListener),
        if (profileListener != null)
          profileSyncListenerProvider.overrideWithValue(profileListener),
      ],
      child: const FlashLearnApp(),
    ));
  });
}

class FlashLearnApp extends ConsumerWidget {
  const FlashLearnApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final settings = ref.watch(settingsProvider);

    // ── Active-time tracking + alarm scheduler lifecycle ──
    // When the active profile is a student/child, start the tracker
    // and the alarm scheduler. Otherwise (teacher/parent/no profile),
    // tear them down so a teacher previewing a student dashboard
    // doesn't spuriously rack up "minutes used today" against their
    // own profile.
    //
    // The whole body is wrapped in try/catch so that a plugin-init or
    // tracker hiccup at the moment a learner becomes active does not
    // surface as the global "Something went wrong" snackbar — that was
    // the user-facing artefact reported after a successful join. The
    // error is still persisted to the Hive diagnostics log via
    // [ErrorHandler.report] under the silent source 'applyLifecycle:silent'.
    void applyLifecycle(UserProfile? next) {
      try {
        final isLearner = next != null &&
            (next.role == UserRole.student || next.role == UserRole.child) &&
            !next.isGuestPlayer;
        if (isLearner) {
          // Wire alarm tap → "Time's Up" lock screen for `lockScreen`
          // actions; for `endSession`, just route home; `notifyOnly`
          // does nothing extra.
          AlarmScheduler.onAlarmFired = (alarm) {
            if (alarm == null) return;
            final ctx = rootNavigatorKey.currentContext;
            if (ctx == null) return;
            try {
              switch (alarm.action) {
                case AlarmAction.lockScreen:
                  GoRouter.of(ctx).go('/time-up-lock');
                case AlarmAction.endSession:
                  GoRouter.of(ctx).go('/home');
                case AlarmAction.notifyOnly:
                  break;
              }
            } catch (e, s) {
              // GoRouter can throw if the navigator is being rebuilt or
              // the alarm fires during a route transition. Log silently
              // so the user doesn't see a generic snackbar — the
              // wall-clock ticker in `lockStateProvider` will surface
              // the lock again within 10 s if it should still apply.
              ErrorHandler.report(e, s, 'OnAlarmFired:silent');
            }
          };
          ActiveTimeTracker.start(next.id);
          // Init returns a Future; failures inside the plugin init or
          // the first reschedule must not escape into the zone, or the
          // global error boundary fires its generic snackbar right
          // after a successful join. Catch + report under a silent source.
          unawaited(
            AlarmScheduler.init(next.id).catchError((e, s) {
              ErrorHandler.report(e, s, 'AlarmScheduler:silent');
            }),
          );
        } else {
          AlarmScheduler.onAlarmFired = null;
          ActiveTimeTracker.stopActive();
          AlarmScheduler.shutdown();
        }
      } catch (e, s) {
        ErrorHandler.report(e, s, 'applyLifecycle:silent');
      }
    }

    // Apply once for the current value, then react to subsequent changes.
    applyLifecycle(ref.read(profileProvider));
    ref.listen(profileProvider, (_, next) => applyLifecycle(next));

    // Check for equipped shop theme (accessibility themes take priority)
    // Watch progress state to rebuild on changes, then read equipped item
    ref.watch(progressProvider);
    final equippedThemeId = ref.read(progressProvider.notifier).getEquippedItemId(
      ShopItemType.theme,
    );

    // Choose theme based on settings — accessibility first, then shop theme
    final ThemeData baseTheme;
    if (settings.highContrastMode) {
      baseTheme = AppTheme.highContrast;
    } else if (settings.darkMode) {
      baseTheme = AppTheme.dark;
    } else {
      baseTheme = AppTheme.shopTheme(equippedThemeId) ?? AppTheme.light;
    }

    // Adjust status bar icons for dark themes
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness:
            (settings.darkMode || settings.highContrastMode)
                ? Brightness.light
                : Brightness.dark,
      ),
    );

    final theme = baseTheme;

    // When reduced motion is enabled, set all flutter_animate durations to zero
    // so every .animate() call throughout the app becomes instant.
    // When reduced motion is enabled, skip all flutter_animate durations.
    // Otherwise use a snappy 250 ms default (lower than 300 ms for 120 Hz feel).
    Animate.defaultDuration = settings.reducedMotion
        ? Duration.zero
        : const Duration(milliseconds: 250);

    return MaterialApp.router(
      title: 'FlashLearn PWD',
      debugShowCheckedModeBanner: false,
      theme: theme,
      routerConfig: router,
      locale: Locale(settings.locale),
      supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      builder: (context, child) {
        // Apply global font scale from settings
        final mediaQuery = MediaQuery.of(context);
        return MediaQuery(
          data: mediaQuery.copyWith(
            textScaler: TextScaler.linear(settings.fontScale),
          ),
          // Wrap in ErrorBoundary to show snackbar for global errors
          // and ConnectivityBanner for offline indicator. The
          // MembershipEvictionGate sits above LockEnforcerGate so an
          // educator-driven removal wins over a time-driven lock —
          // no point showing a lock screen for a profile that just
          // got signed out anyway.
          child: ErrorBoundary(
            child: ConnectivityBanner(
              child: MembershipEvictionGate(
                child: LockEnforcerGate(
                  child: child ?? const SizedBox.shrink(),
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}
