import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'l10n/app_localizations.dart';
import 'core/security/owner_uid_migration.dart';
import 'core/security/pin_migration.dart';
import 'core/security/username_migration.dart';
import 'core/services/action_clip_service.dart';
import 'core/services/active_time_tracker.dart';
import 'core/services/alarm_scheduler.dart';
import 'core/services/flashcard_photo_service.dart';
import 'core/services/notification_service.dart';
import 'core/services/analytics_service.dart';
import 'core/services/firebase_service.dart';
import 'core/services/profile_sync_listener.dart';
import 'core/services/progress_sync_listener.dart';
import 'core/services/sync_service.dart';
import 'data/models/alarm_action.dart';
import 'data/models/enums.dart';
import 'data/models/models.dart';
import 'features/classroom/widgets/lock_enforcer_gate.dart';
import 'features/onboarding/widgets/membership_eviction_gate.dart';
// Generated by `flutterfire configure` — required for web and recommended
// on all platforms. If you haven't run that command yet, see the README.
import 'firebase_options.dart';
import 'core/theme/app_theme.dart';
import 'core/utils/error_handler.dart';
import 'data/local/hive_service.dart';
import 'data/local/local_repository.dart';
import 'data/remote/firestore_repository.dart';

import 'data/models/shop_data.dart';
import 'navigation/app_router.dart';
import 'providers/app_providers.dart';
import 'widgets/connectivity_banner.dart';
import 'widgets/error_boundary.dart';
import 'core/services/sync_queue/sync_queue_service.dart';
import 'widgets/sync_status_widget.dart';

SystemUiOverlayStyle _systemUiStyleFor({required bool isDark}) {
  final iconBrightness = isDark ? Brightness.light : Brightness.dark;
  return SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: iconBrightness,
    statusBarBrightness: isDark ? Brightness.dark : Brightness.light,
    systemNavigationBarColor: Colors.transparent,
    systemNavigationBarIconBrightness: iconBrightness,
    systemNavigationBarDividerColor: Colors.transparent,
    systemNavigationBarContrastEnforced: false,
    systemStatusBarContrastEnforced: false,
  );
}

void main() {
  // Wrap the entire startup in a guarded zone so that
  // ensureInitialized() and runApp() share the SAME zone.
  // This prevents the "Zone mismatch" error.
  ErrorHandler.runGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Install global error handling FIRST
    ErrorHandler.init();
    setupErrorWidget();

    // ─── High Refresh-Rate Performance Configuration ──────
    // Flutter 3.x automatically targets the display's native refresh rate
    // (120 Hz on Honor Pad X8a) so no manual configuration is needed.

    // Pointer-event resampling stays OFF (Flutter's default). When enabled,
    // touch events are queued and replayed against the frame clock; on
    // tablets whose input timestamps drift from that clock (or when a frame
    // janks) the queue flushes late, so single taps feel dead and users end
    // up tapping repeatedly. Direct dispatch keeps every tap immediate.
    GestureBinding.instance.resamplingEnabled = false;

    // Increase decoded image cache for a 4 GB device with heavy flashcard
    // images. Default is 100 MB; we raise to 256 MB so scrolling large
    // grids doesn't repeatedly decode the same assets.
    PaintingBinding.instance.imageCache.maximumSizeBytes = 256 << 20; // 256 MB
    PaintingBinding.instance.imageCache.maximumSize = 200; // up to 200 images

    // Prevent Google Fonts from making HTTP requests at runtime.
    // Fonts are bundled in the google_fonts/ directory instead.
    // This avoids ANR on devices with slow or no internet.
    GoogleFonts.config.allowRuntimeFetching = false;

    // Orientation: allow landscape on tablets (≥600 dp shortest side),
    // keep portrait-only on phones. The check uses the first view's
    // physical size divided by its device pixel ratio so we don't need
    // a MediaQuery (which requires a build context).
    final firstView =
        WidgetsBinding.instance.platformDispatcher.views.first;
    final dpr = firstView.devicePixelRatio;
    final logicalSize = firstView.physicalSize / dpr;
    final shortestSide = logicalSize.shortestSide;
    final isTabletForm = shortestSide >= 600;
    await SystemChrome.setPreferredOrientations(
      isTabletForm
          ? const [
              DeviceOrientation.portraitUp,
              DeviceOrientation.portraitDown,
              DeviceOrientation.landscapeLeft,
              DeviceOrientation.landscapeRight,
            ]
          : const [
              DeviceOrientation.portraitUp,
              DeviceOrientation.portraitDown,
            ],
    );

    // Edge-to-edge: draw under status + nav bars. Android 15 (targetSdk
    // 35+) enforces this anyway; setting it explicitly gives consistent
    // behavior on Android 10+. We can't await this on older versions
    // where it's a no-op, so fire-and-forget.
    await SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);

    // Transparent system bars at startup. Per-theme icon brightness is
    // re-applied inside [FlashLearnApp.build] once we know the theme.
    SystemChrome.setSystemUIOverlayStyle(_systemUiStyleFor(isDark: false));

    // Initialize Hive, Firebase, and Notifications in parallel
    // (they are independent of each other)
    await Future.wait([
      HiveService.init(),
      // Parse the media manifests (real photos + "Show Me" action clips) so
      // FlashcardImage / the Picture-Word game / the viewer know what's
      // available by first render. Both swallow errors and stay dormant when
      // no manifest URL is configured, so this never blocks or breaks startup.
      FlashcardPhotoService.load(),
      ActionClipService.load(),
      FirebaseService.init(options: DefaultFirebaseOptions.currentPlatform),
      NotificationService.init(
        onNotificationTap: (payload) { 
          WidgetsBinding.instance.addPostFrameCallback((_) {
            final ctx = rootNavigatorKey.currentContext;
            if (ctx == null) return;
            switch (payload) {
              
              case 'daily_challenge':
                GoRouter.of(ctx).go('/home');
              case 'vocab_review':
                GoRouter.of(ctx).go('/smart-review');
              default:
                GoRouter.of(ctx).go('/home');
            }
          });
        },
      ),
    ]);

    // Open the error logs box (after Hive.init)
    await Hive.openBox('error_logs');

    // Migrate any plaintext PINs to salted PBKDF2 hashes before the first
    // PIN-gated screen can be reached. Local-only and idempotent — a 
    // settings flag and per-profile guards prevent double-hashing.
    await PinMigration.runIfNeeded();

    // Build the sync plumbing now — constructors are I/O-free and the
    // provider overrides below need the instances synchronously. The
    // network side (listeners, queue drain) starts in the background
    // chain after sign-in.
    SyncService? syncInstance;
    SyncQueueService? queueInstance;
    ProgressSyncListener? progressListener;
    ProfileSyncListener? profileListener;
    if (FirebaseService.isConfigured) {
      syncInstance = SyncService(
        local: const LocalRepository(),
        remote: const FirestoreRepository(),
      );
      queueInstance = syncInstance.queueService;

      // Bidirectional sync: subscribe to remote progress for every
      // profile on this device so updates from other devices land in
      // Hive and refresh the UI without a manual reload.
      progressListener = ProgressSyncListener();

      // Mirror listener for `profiles/{id}` — picks up educator-driven
      // name patches (Manage Classes > Rename, Home Group > Rename) so
      // the learner's own device shows the new name without a relaunch.
      profileListener = ProfileSyncListener();
    }

    // Everything that may touch the network runs AFTER the first frame,
    // behind the splash screen, so a slow or absent connection can never
    // hold the app on the native splash. Order inside the chain matters:
    // sign-in mints the auth uid that the migrations stamp onto local
    // data and that Firestore security rules require for the listeners.
    final sync = syncInstance;
    final queue = queueInstance;
    final progressSync = progressListener;
    final profileSync = profileListener;
    unawaited(() async {
      try {
        // Anonymous auth so every Firestore write carries an auth uid.
        await FirebaseService.signInAnonymously();

        // Opt-in telemetry (Crashlytics + Analytics). Reads the persisted
        // opt-in flag from Hive — default OFF, so nothing is sent until an
        // educator opts in via Settings → "Help improve the app".
        await AnalyticsService.initialize();

        // Claim ownership of pre-auth profiles for this device's uid.
        // Skips without setting its done-flag when sign-in didn't
        // complete, so it retries on the next boot.
        await OwnerUidMigration.runIfNeeded();

        // Mint a messaging handle for every legacy profile that doesn't
        // have one yet. Idempotent (flag + per-profile null check).
        await UsernameMigration.runIfNeeded();

        // With auth in place, open the sync pipes: connectivity listener,
        // pending-write drain, and the remote progress/profile mirrors.
        sync?.startListening();
        queue?.processQueue();
        progressSync?.start();
        profileSync?.start();
      } catch (e, s) {
        // Background startup must never pop the global error snackbar —
        // every step retries on the next boot or on demand (ensureSignedIn).
        ErrorHandler.report(e, s, 'startupBackground:silent');
      }
    }());

    runApp(ProviderScope(
      overrides: [
        if (syncInstance != null)
          syncServiceProvider.overrideWithValue(syncInstance),
        if (queueInstance != null)
          syncQueueServiceProvider.overrideWithValue(queueInstance),
        if (progressListener != null)
          progressSyncListenerProvider.overrideWithValue(progressListener),
        if (profileListener != null)
          profileSyncListenerProvider.overrideWithValue(profileListener),
      ],
      child: const FlashLearnApp(),
    ));
  });
}

class FlashLearnApp extends ConsumerWidget {
  const FlashLearnApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final settings = ref.watch(settingsProvider);

    // ── Active-time tracking + alarm scheduler lifecycle ──
    // When the active profile is a student/child, start the tracker
    // and the alarm scheduler. Otherwise (teacher/parent/no profile),
    // tear them down so a teacher previewing a student dashboard
    // doesn't spuriously rack up "minutes used today" against their
    // own profile.
    //
    // The whole body is wrapped in try/catch so that a plugin-init or
    // tracker hiccup at the moment a learner becomes active does not
    // surface as the global "Something went wrong" snackbar — that was
    // the user-facing artefact reported after a successful join. The
    // error is still persisted to the Hive diagnostics log via
    // [ErrorHandler.report] under the silent source 'applyLifecycle:silent'.
    void applyLifecycle(UserProfile? next) {
      try {
        final isLearner = next != null &&
            (next.role == UserRole.student || next.role == UserRole.child) &&
            !next.isGuestPlayer;
        if (isLearner) {
          // Wire alarm tap → "Time's Up" lock screen for `lockScreen`
          // actions; for `endSession`, just route home; `notifyOnly`
          // does nothing extra.
          AlarmScheduler.onAlarmFired = (alarm) {
            if (alarm == null) return;
            final ctx = rootNavigatorKey.currentContext;
            if (ctx == null) return;
            try {
              switch (alarm.action) {
                case AlarmAction.lockScreen:
                  GoRouter.of(ctx).go('/time-up-lock');
                case AlarmAction.endSession:
                  GoRouter.of(ctx).go('/home');
                case AlarmAction.notifyOnly:
                  break;
              }
            } catch (e, s) {
              // GoRouter can throw if the navigator is being rebuilt or
              // the alarm fires during a route transition. Log silently
              // so the user doesn't see a generic snackbar — the
              // wall-clock ticker in `lockStateProvider` will surface
              // the lock again within 10 s if it should still apply.
              ErrorHandler.report(e, s, 'OnAlarmFired:silent');
            }
          };
          ActiveTimeTracker.start(next.id);
          // Init returns a Future; failures inside the plugin init or
          // the first reschedule must not escape into the zone, or the
          // global error boundary fires its generic snackbar right
          // after a successful join. Catch + report under a silent source.
          unawaited(
            AlarmScheduler.init(next.id).catchError((e, s) {
              ErrorHandler.report(e, s, 'AlarmScheduler:silent');
            }),
          );
        } else {
          AlarmScheduler.onAlarmFired = null;
          ActiveTimeTracker.stopActive();
          AlarmScheduler.shutdown();
        }
      } catch (e, s) {
        ErrorHandler.report(e, s, 'applyLifecycle:silent');
      }
    }

    // Apply once for the current value, then react to subsequent changes.
    applyLifecycle(ref.read(profileProvider));
    ref.listen(profileProvider, (_, next) => applyLifecycle(next));

    // Check for equipped shop theme (acc essibility themes take priority)
    // Watch progress state to rebuild on changes, then read equipped item
    ref.watch(progressProvider);
    final equippedThemeId = ref.read(progressProvider.notifier).getEquippedItemId(
      ShopItemType.theme,
    );

    // Active profile drives the per-group theme below; watch so the app
    // re-themes when the user switches profiles.
    final profileForTheme = ref.watch(profileProvider);

    // Choose theme based on settings — accessibility first, then shop theme,
    // then the profile-group theme (Classroom blue / Family-group coral).
    // Cascade order: high-contrast > dyslexia > (dark mode × shop theme) >
    // dark mode > shop theme > group theme > light. The dark-mode × shop-theme
    // combo matters because users who paid for a shop theme expect their
    // palette to follow them into night mode instead of being kicked to stock
    // dark. Group themes sit at the bottom so accessibility modes and a
    // purchased shop theme always win.
    final ThemeData baseTheme;
    if (settings.highContrastMode) {
      baseTheme = AppTheme.highContrast;
    } else if (settings.dyslexiaMode) {
      baseTheme = AppTheme.dyslexia;
    } else if (settings.darkMode) {
      baseTheme = AppTheme.shopThemeDark(equippedThemeId) ?? AppTheme.dark;
    } else {
      baseTheme = AppTheme.shopTheme(equippedThemeId) ??
          AppTheme.groupTheme(profileForTheme?.role) ??
          AppTheme.light;
    }

    // Adjust both status bar AND nav bar icons for dark themes. The
    // nav bar piece matters under edge-to-edge — without it, light icons
    // on a light Flutter background go invisible after a theme toggle.
    SystemChrome.setSystemUIOverlayStyle(
      _systemUiStyleFor(
        isDark: settings.darkMode || settings.highContrastMode,
      ),
    );

    // Reduced-motion contract: when on, strip page-route transitions too
    // so navigation is instant (Animate.defaultDuration already covers
    // in-screen flutter_animate calls).
    final theme = settings.reducedMotion
        ? AppTheme.withReducedMotion(baseTheme)
        : baseTheme;

    // When reduced motion is enabled, set all flutter_animate durations to zero
    // so every .animate() call throughout the app becomes instant.
    // When reduced motion is enabled, skip all flutter_animate durations.
    // Otherwise use a snappy 250 ms default (lower than 300 ms for 120 Hz feel).
    Animate.defaultDuration = settings.reducedMotion
        ? Duration.zero
        : const Duration(milliseconds: 250);

    return MaterialApp.router(
      title: 'FlashLearn PWD',
      debugShowCheckedModeBanner: false,
      theme: theme,
      routerConfig: router,
      locale: Locale(settings.locale),
      supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      builder: (context, child) {
        // Apply global font scale from settings, multiplied against the
        // OS scale, then clamp the product into a layout-safe range so
        // extreme system font scales (some Android skins go to 2.0) don't
        // overflow game/flashcard tiles.
        final mediaQuery = MediaQuery.of(context);
        final systemScale = mediaQuery.textScaler.scale(1.0);
        final combined = (systemScale * settings.fontScale).clamp(0.85, 1.5);
        return MediaQuery(
          data: mediaQuery.copyWith(
            textScaler: TextScaler.linear(combined),
          ),
          // ErrorBoundary (global error snackbars), ConnectivityBanner (offline
          // indicator), then MembershipEvictionGate above LockEnforcerGate so an
          // educator-driven removal wins over a time-driven lock.
          child: ErrorBoundary(
            child: ConnectivityBanner(
              child: MembershipEvictionGate(
                child: LockEnforcerGate(
                  child: child ?? const SizedBox.shrink(),
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}

// Scroll behavior intentionally stays at the MaterialScrollBehavior default.
// A previous override added PointerDeviceKind.mouse to dragDevices, but the
// drag slop for a mouse is 1 logical pixel — any click that moved ≥1px inside
// a scrollable became a micro-drag that cancelled the tap, so buttons needed
// several clicks. The default set (touch/stylus/trackpad/unknown) also keeps
// Android Voice Access scrolling working; mouse users scroll with the wheel.
