import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'l10n/app_localizations.dart';
import 'core/security/owner_uid_migration.dart';
import 'core/security/pin_migration.dart';
import 'core/services/notification_service.dart';
import 'core/services/firebase_service.dart';
import 'core/services/progress_sync_listener.dart';
import 'core/services/sync_service.dart';
// Generated by `flutterfire configure` — required for web and recommended
// on all platforms. If you haven't run that command yet, see the README.
import 'firebase_options.dart';
import 'core/theme/app_theme.dart';
import 'core/utils/error_handler.dart';
import 'data/local/hive_service.dart';
import 'data/local/local_repository.dart';
import 'data/remote/firestore_repository.dart';
import 'data/models/shop_data.dart';
import 'navigation/app_router.dart';
import 'providers/app_providers.dart';
import 'widgets/connectivity_banner.dart';
import 'widgets/error_boundary.dart';
import 'core/services/sync_queue/sync_queue_service.dart';
import 'widgets/sync_status_widget.dart';

void main() {
  // Wrap the entire startup in a guarded zone so that
  // ensureInitialized() and runApp() share the SAME zone.
  // This prevents the "Zone mismatch" error.
  ErrorHandler.runGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Install global error handling FIRST
    ErrorHandler.init();
    setupErrorWidget();

    // ─── High Refresh-Rate Performance Configuration ──────
    // Flutter 3.x automatically targets the display's native refresh rate
    // (120 Hz on Honor Pad X8a) so no manual configuration is needed.

    // Enable pointer-event resampling to align touch events with frame
    // boundaries — reduces perceived input latency on high-Hz displays.
    GestureBinding.instance.resamplingEnabled = true;

    // Increase decoded image cache for a 4 GB device with heavy flashcard
    // images. Default is 100 MB; we raise to 256 MB so scrolling large
    // grids doesn't repeatedly decode the same assets.
    PaintingBinding.instance.imageCache.maximumSizeBytes = 256 << 20; // 256 MB
    PaintingBinding.instance.imageCache.maximumSize = 200; // up to 200 images

    // Prevent Google Fonts from making HTTP requests at runtime.
    // Fonts are bundled in the google_fonts/ directory instead.
    // This avoids ANR on devices with slow or no internet.
    GoogleFonts.config.allowRuntimeFetching = false;

    // Lock to portrait on tablets
    await SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    // Transparent status bar
    SystemChrome.setSystemUIOverlayStyle(
      const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness: Brightness.dark,
      ),
    );

    // Initialize Hive, Firebase, and Notifications in parallel
    // (they are independent of each other)
    await Future.wait([
      HiveService.init(),
      FirebaseService.init(options: DefaultFirebaseOptions.currentPlatform),
      NotificationService.init(
        onNotificationTap: (payload) {
          WidgetsBinding.instance.addPostFrameCallback((_) {
            final ctx = rootNavigatorKey.currentContext;
            if (ctx == null) return;
            switch (payload) {
              case 'daily_challenge':
                GoRouter.of(ctx).go('/home');
              case 'vocab_review':
                GoRouter.of(ctx).go('/smart-review');
              default:
                GoRouter.of(ctx).go('/home');
            }
          });
        },
      ),
    ]);

    // Open the error logs box (after Hive.init)
    await Hive.openBox('error_logs');

    // Sign in anonymously so every Firestore write carries an auth uid.
    // Must run before OwnerUidMigration (which stamps that uid onto
    // pre-auth profiles) and before any sync/queue activity.
    await FirebaseService.signInAnonymously();

    // Migrate any plaintext PINs to salted PBKDF2 hashes. Idempotent —
    // a settings flag and per-profile guards prevent double-hashing.
    await PinMigration.runIfNeeded();

    // Claim ownership of pre-auth profiles for this device's uid.
    // Idempotent — a Hive flag prevents re-runs.
    await OwnerUidMigration.runIfNeeded();

    // Start offline-first sync service (after Firebase init)
    SyncService? syncInstance;
    SyncQueueService? queueInstance;
    ProgressSyncListener? progressListener;
    if (FirebaseService.isConfigured) {
      syncInstance = SyncService(
        local: const LocalRepository(),
        remote: const FirestoreRepository(),
      );
      syncInstance.startListening();
      queueInstance = syncInstance.queueService;

      // Process any pending queue items if we're online at launch
      queueInstance?.processQueue();

      // Bidirectional sync: subscribe to remote progress for every
      // profile on this device so updates from other devices land in
      // Hive and refresh the UI without a manual reload.
      progressListener = ProgressSyncListener();
      progressListener.start();
    }

    runApp(ProviderScope(
      overrides: [
        if (syncInstance != null)
          syncServiceProvider.overrideWithValue(syncInstance),
        if (queueInstance != null)
          syncQueueServiceProvider.overrideWithValue(queueInstance),
        if (progressListener != null)
          progressSyncListenerProvider.overrideWithValue(progressListener),
      ],
      child: const FlashLearnApp(),
    ));
  });
}

class FlashLearnApp extends ConsumerWidget {
  const FlashLearnApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final settings = ref.watch(settingsProvider);

    // Check for equipped shop theme (accessibility themes take priority)
    // Watch progress state to rebuild on changes, then read equipped item
    ref.watch(progressProvider);
    final equippedThemeId = ref.read(progressProvider.notifier).getEquippedItemId(
      ShopItemType.theme,
    );

    // Choose theme based on settings — accessibility first, then shop theme
    final ThemeData baseTheme;
    if (settings.highContrastMode) {
      baseTheme = AppTheme.highContrast;
    } else if (settings.darkMode) {
      baseTheme = AppTheme.dark;
    } else {
      baseTheme = AppTheme.shopTheme(equippedThemeId) ?? AppTheme.light;
    }

    // Adjust status bar icons for dark themes
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness:
            (settings.darkMode || settings.highContrastMode)
                ? Brightness.light
                : Brightness.dark,
      ),
    );

    final theme = baseTheme;

    // When reduced motion is enabled, set all flutter_animate durations to zero
    // so every .animate() call throughout the app becomes instant.
    // When reduced motion is enabled, skip all flutter_animate durations.
    // Otherwise use a snappy 250 ms default (lower than 300 ms for 120 Hz feel).
    Animate.defaultDuration = settings.reducedMotion
        ? Duration.zero
        : const Duration(milliseconds: 250);

    return MaterialApp.router(
      title: 'FlashLearn PWD',
      debugShowCheckedModeBanner: false,
      theme: theme,
      routerConfig: router,
      locale: Locale(settings.locale),
      supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      builder: (context, child) {
        // Apply global font scale from settings
        final mediaQuery = MediaQuery.of(context);
        return MediaQuery(
          data: mediaQuery.copyWith(
            textScaler: TextScaler.linear(settings.fontScale),
          ),
          // Wrap in ErrorBoundary to show snackbar for global errors
          // and ConnectivityBanner for offline indicator
          child: ErrorBoundary(
            child: ConnectivityBanner(
              child: child ?? const SizedBox.shrink(),
            ),
          ),
        );
      },
    );
  }
}
