/// Message role in the tutor conversation
enum TutorMessageRole { tutor, student, system }

/// A single message in the tutor chat
class TutorMessage {
  final String id;
  final TutorMessageRole role;
  final String content;
  final DateTime timestamp;
  final TutorAction? action; // Optional interactive action

  const TutorMessage({
    required this.id,
    required this.role,
    required this.content,
    required this.timestamp,
    this.action,
  });

  /// JSON-safe map for Hive persistence (raw maps, no Hive adapter needed —
  /// mirrors the SpacedRepetitionService storage pattern).
  Map<String, dynamic> toJson() => {
        'id': id,
        'role': role.name,
        'content': content,
        'timestamp': timestamp.toIso8601String(),
        if (action != null) 'action': action!.toJson(),
      };

  factory TutorMessage.fromJson(Map<String, dynamic> json) => TutorMessage(
        id: json['id'] as String,
        role: _roleFromName(json['role'] as String?),
        content: json['content'] as String? ?? '',
        timestamp: DateTime.tryParse(json['timestamp'] as String? ?? '') ??
            DateTime.now(),
        action: json['action'] == null
            ? null
            : TutorAction.fromJson(
                Map<String, dynamic>.from(json['action'] as Map)),
      );

  static TutorMessageRole _roleFromName(String? name) {
    for (final r in TutorMessageRole.values) {
      if (r.name == name) return r;
    }
    return TutorMessageRole.tutor;
  }
}

/// An interactive action embedded in a tutor message
enum TutorActionType {
  quickQuiz,        // Show a quick quiz question
  practiceRedirect, // Suggest going to a specific practice
  encouragement,    // Special encouragement with celebration
  wordOfTheDay,     // Show a vocabulary word
  startLesson,      // Offer to start today's personalized learning plan
  pickInterests,    // Tappable favorite-topic chips (or a recorded pick)
  /// A word being re-taught after a wrong answer. Carries only [wordId]; it
  /// asks nothing, but the id lets the bubble show the card's photo / sign so
  /// the correction lands through more than one sense.
  reteach,
}

class TutorAction {
  final TutorActionType type;
  final String? targetRoute; // For practiceRedirect
  final String? question;    // For quickQuiz
  final List<String>? options; // For quickQuiz
  final String? correctAnswer; // For quickQuiz
  /// Flashcard id backing a quickQuiz, so a correct answer can be recorded
  /// against spaced-repetition / progress tracking. Null for non-quiz actions.
  final String? wordId;
  /// Category label backing a quickQuiz word (for progress attribution).
  final String? categoryLabel;
  /// For [TutorActionType.startLesson]: the flashcard ids in today's plan.
  final List<String>? planWordIds;

  const TutorAction({
    required this.type,
    this.targetRoute,
    this.question,
    this.options,
    this.correctAnswer,
    this.wordId,
    this.categoryLabel,
    this.planWordIds,
  });

  Map<String, dynamic> toJson() => {
        'type': type.name,
        if (targetRoute != null) 'targetRoute': targetRoute,
        if (question != null) 'question': question,
        if (options != null) 'options': options,
        if (correctAnswer != null) 'correctAnswer': correctAnswer,
        if (wordId != null) 'wordId': wordId,
        if (categoryLabel != null) 'categoryLabel': categoryLabel,
        if (planWordIds != null) 'planWordIds': planWordIds,
      };

  factory TutorAction.fromJson(Map<String, dynamic> json) => TutorAction(
        type: _typeFromName(json['type'] as String?),
        targetRoute: json['targetRoute'] as String?,
        question: json['question'] as String?,
        options: (json['options'] as List?)?.map((e) => e as String).toList(),
        correctAnswer: json['correctAnswer'] as String?,
        wordId: json['wordId'] as String?,
        categoryLabel: json['categoryLabel'] as String?,
        planWordIds:
            (json['planWordIds'] as List?)?.map((e) => e as String).toList(),
      );

  static TutorActionType _typeFromName(String? name) {
    for (final t in TutorActionType.values) {
      if (t.name == name) return t;
    }
    return TutorActionType.encouragement;
  }
}

/// Hint generated by the tutor engine for weak areas
class TutorHint {
  final String category;
  final String tip;
  final String tipFilipino;

  const TutorHint({
    required this.category,
    required this.tip,
    required this.tipFilipino,
  });
}

/// Lightweight, cumulative counters for the tutor — surfaced in the header as a
/// "what you've done with your buddy" strip. Persisted via [TutorMemoryService].
class TutorStats {
  final int questionsAsked;
  final int quizzesAnswered;
  final int quizzesCorrect;
  final int lessonsCompleted;

  const TutorStats({
    this.questionsAsked = 0,
    this.quizzesAnswered = 0,
    this.quizzesCorrect = 0,
    this.lessonsCompleted = 0,
  });

  TutorStats copyWith({
    int? questionsAsked,
    int? quizzesAnswered,
    int? quizzesCorrect,
    int? lessonsCompleted,
  }) =>
      TutorStats(
        questionsAsked: questionsAsked ?? this.questionsAsked,
        quizzesAnswered: quizzesAnswered ?? this.quizzesAnswered,
        quizzesCorrect: quizzesCorrect ?? this.quizzesCorrect,
        lessonsCompleted: lessonsCompleted ?? this.lessonsCompleted,
      );

  Map<String, dynamic> toJson() => {
        'questionsAsked': questionsAsked,
        'quizzesAnswered': quizzesAnswered,
        'quizzesCorrect': quizzesCorrect,
        'lessonsCompleted': lessonsCompleted,
      };

  factory TutorStats.fromJson(Map<String, dynamic> json) => TutorStats(
        questionsAsked: json['questionsAsked'] as int? ?? 0,
        quizzesAnswered: json['quizzesAnswered'] as int? ?? 0,
        quizzesCorrect: json['quizzesCorrect'] as int? ?? 0,
        lessonsCompleted: json['lessonsCompleted'] as int? ?? 0,
      );
}

/// The full persisted state of a learner's tutor relationship.
class TutorMemory {
  /// Most-recent chat messages (capped on save to bound storage).
  final List<TutorMessage> messages;
  final TutorStats stats;

  /// `yyyy-mm-dd` of the day the learner last completed a learning plan.
  /// Guards the once-per-day lesson star reward.
  final String? lastPlanDate;

  /// Flashcard ids in the plan offered for [lastPlanDate].
  final List<String> planWordIds;

  /// Topics the learner explicitly picked as favorites — [FlashcardCategory]
  /// enum *names* (stable across label/locale changes), most recent first.
  final List<String> favoriteCategories;

  /// Implicit per-topic affinity learned from behavior (asking about a
  /// category, answering its quizzes), keyed by [FlashcardCategory] name.
  final Map<String, double> interestScores;

  /// Ids of interactive bubbles the learner has actually resolved — answered
  /// quizzes and used favorite-topic pickers.
  ///
  /// Persisted so a restored conversation locks *only* what was really
  /// answered. Both tutor surfaces share this set, so a picker offered in the
  /// floating companion is still live after expanding to the full screen.
  /// Null (rather than empty) marks pre-existing memory saved before this was
  /// tracked — see [TutorMemoryService.getMemory] for the legacy fallback.
  final Set<String>? answeredIds;

  const TutorMemory({
    this.messages = const [],
    this.stats = const TutorStats(),
    this.lastPlanDate,
    this.planWordIds = const [],
    this.favoriteCategories = const [],
    this.interestScores = const {},
    this.answeredIds,
  });

  TutorMemory copyWith({
    List<TutorMessage>? messages,
    TutorStats? stats,
    String? lastPlanDate,
    List<String>? planWordIds,
    List<String>? favoriteCategories,
    Map<String, double>? interestScores,
    Set<String>? answeredIds,
  }) =>
      TutorMemory(
        messages: messages ?? this.messages,
        stats: stats ?? this.stats,
        lastPlanDate: lastPlanDate ?? this.lastPlanDate,
        planWordIds: planWordIds ?? this.planWordIds,
        favoriteCategories: favoriteCategories ?? this.favoriteCategories,
        interestScores: interestScores ?? this.interestScores,
        answeredIds: answeredIds ?? this.answeredIds,
      );
}
