/// Message role in the tutor conversation
enum TutorMessageRole { tutor, student, system }

/// A single message in the tutor chat
class TutorMessage {
  final String id;
  final TutorMessageRole role;
  final String content;
  final DateTime timestamp;
  final TutorAction? action; // Optional interactive action

  const TutorMessage({
    required this.id,
    required this.role,
    required this.content,
    required this.timestamp,
    this.action,
  });
}

/// An interactive action embedded in a tutor message
enum TutorActionType {
  quickQuiz,        // Show a quick quiz question
  practiceRedirect, // Suggest going to a specific practice
  encouragement,    // Special encouragement with celebration
  wordOfTheDay,     // Show a vocabulary word
}

class TutorAction {
  final TutorActionType type;
  final String? targetRoute; // For practiceRedirect
  final String? question;    // For quickQuiz
  final List<String>? options; // For quickQuiz
  final String? correctAnswer; // For quickQuiz

  const TutorAction({
    required this.type,
    this.targetRoute,
    this.question,
    this.options,
    this.correctAnswer,
  });
}

/// Hint generated by the tutor engine for weak areas
class TutorHint {
  final String category;
  final String tip;
  final String tipFilipino;

  const TutorHint({
    required this.category,
    required this.tip,
    required this.tipFilipino,
  });
}
